# Generated by Django 3.2.8 on 2021-11-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostpoststory',
            name='follow',
            field=models.TextField(blank=True),
        ),
    ]
